

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd opt/bin/tomcat/webapps
          rm -rf *
          cp /home/runner/work/CIwithmavenactions/CIwithmavenactions/target/gs-maven-0.1.0-shaded.jar .
          /opt/bin/tomcat/bin/shutdown.sh
          /opt/bin/tomcat/bin/startup.sh

   